openapi: 3.1.0

info:
  title: "Calculator REST API"
  description: "Калькулятор сервиса NeoLoan"
  contact:
    name: Igor Petrov
    url: "https://github.com/IgorPetrovcm"
  version: "1.0-SNAPSHOT"

paths:
  /calculator/offers:
    description: "Расчет возможных условий кредита"
    post:
      requestBody:
        description: "Данные заявки на кредит"
        content:
          application/json:
            schema:
              type: LoanStatementRequest
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: LoanOffer

  /calculator/calc:
    description: "Скоринг данных"
    post:
      requestBody:
        description: "Данные для скоринга"
        content:
          application/json:
            schema:
              type: ScoringData
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                type: Credit