openapi: 3.1.0

info:
  title: "Fields for models"
  version: 1.0-SNAPSHOT

# paths:
#   /:

components:
  schemas:
    Name:
      type: string
      minLength: 2
      maxLength: 30

    Amount:
      type: number
      format: decimal
      minimum: 20000
