openapi: 3.1.0

info:
  title: "DTO models for Calculator"
  description: "Here is a description of all DTO models for Calculator"
  contact:
    name: Igor Petrov
    url: "https://github.com/IgorPetrovcm"
  version: "1.0-SNAPSHOT"

components:
  schemas:
    LoanStatementRequest:
      required:
        - amount
        - term
        - firstName
        - lastName
        - email
        - birthdate
        - passportSeries
        - passportNumber
      properties:
        amount:
          $ref: 'components.yaml#/components/schemas/Amount'
        term:
          type: integer
          minimum: 6
        firstName:
          allOf:
            - $ref: 'components.yaml#/components/schemas/Name'
        lastName:
          allOf:
            - $ref: 'components.yaml#/components/schemas/Name'
        middleName:
          allOf:
            - $ref: 'components.yaml#/components/schemas/Name'
          nullable: true
        email:
          type: string
          format: email
          pattern: "^[a-z0-9A-Z_!#$%&'*+/=?`{|}~^.-]+@[a-z0-9A-Z.-]+$"
        birthdate:
          type: string
          format: date
        passportSeries:
          type: string
          minLength: 4
          maxLength: 4
        passportNumber:
          type: string
          minLength: 6
          maxLength: 6

    LoanOffer:
      require:
        - statementId
        - totalAmount
      properties:
        statementId:
          type: string
          format: uuid
        requestedAmount:
          $ref: 'components.yaml#/components/schemas/Amount'
        totalAmount:
          $ref: 'components.yaml#/components/schemas/Amount'
          minimum: 20000
        term:
          type: integer
        monthlyPayment:
          type: number
          format: decimal
        rate:
          type: number
          format: decimal
        isInsuranceEnabled:
          type: boolean
        isSalaryClient:
          type: boolean
